### ISSUE TITLE
Table of contents does not generate unique heading urls

### ISSUE THREAD

**Issue by Qrbaker** [TrueBrain/wikitexthtml#24]
Example: https://wiki.craftycontrol.com/en/3/Install%20Guides

Try clicking on any heading called "installation". The links will all go to the first instance (`#installation`). The wiki software correctly disambiguates subsequent heading links as `#installation_2`, `#installation_3` etc. but the generated TOC doesn't appear to use it.

**Comment by TrueBrain** [comment]
https://github.com/TrueBrain/wikitexthtml/blob/92292187272c74fbe5e488114a46a278ca8fd149/wikitexthtml/render/section.py#L147 does add a sequence number behind slugs if there are more than one in a page, but https://github.com/TrueBrain/wikitexthtml/blob/92292187272c74fbe5e488114a46a278ca8fd149/wikitexthtml/render/section.py#L74 does not. This is not in sync.

I guess best way to solve it is to do a similar trick in the second place as in the first, but it might need some code cleanup to make that look pretty.
