### ISSUE TITLE
Gallery tag: TypeError: file_get_img() missing 1 required positional argument: 'thumb'

### ISSUE THREAD

**Issue by sonn-gamm** [TrueBrain/wikitexthtml#33]
Hi!

Thanks a lot for this library. I am learning Python so I might be missing something obvious, as well as I am slow figuring out how the code works.

I am having problems when parsing a `<gallery>` tag. With an input such as:

```
<gallery mode=packed>
Example.jpg|example of normal length caption maybe
Line_sensor.JPG
Example.jpg|example of normal length caption maybe
</gallery>
```

I get back an empty `<ul></ul>` element, which I read as if the syntax inside the gallery tag is not valid? Though MediaWiki renders this fine (argh!).

With an input of:

```
<gallery caption="Sample gallery" widths="100px" heights="100px" perrow="6">
File:Drenthe-Position.png|[[w:Drenthe|Drenthe]], the least crowded province
File:Flevoland-Position.png
File:Friesland-Position.png|[[w:Friesland|Friesland]] has many lakes
File:Gelderland-Position.png
File:Groningen-Position.png
File:Limburg-Position.png
File:Noord_Brabant-Position.png
File:Noord_Holland-Position.png
Overijssel-Position.png
Utrecht-Position.png
Zuid_Holland-Position.png|[[w:South Holland|South Holland]], the most crowded province
Zeeland-Position.png|link=nl:Zeeland (provincie)
</gallery>
```

taken from <https://meta.wikimedia.org/wiki/Help:Images_and_other_uploaded_files#Gallery> I get back the following error:

```
TypeError: file_get_img() missing 1 required positional argument: 'thumb'
```

pointing to L60 of [wikitexthtml/render/tags/gallery.py](https://github.com/TrueBrain/wikitexthtml/blob/77a08af95ab9ad5fa5ef4e3a74b4205e75d63b6e/wikitexthtml/render/tags/gallery.py#L60).

What do you think is happening, and should I give you more info?

Thanks!

**Comment by TrueBrain** [comment]
Great to hear people are using this library; I still love this project :)

First, your second question. Please make sure you implemented `file_get_img` with `def file_get_img(self, url: str, thumb: Optional[int] = None) -> str:`. It sounds to me the `= None` fell off in your implementation.

Second, your first question: you should be receiving an error on the instance mentioning that `Gallery entry "Example.jpg" is not a valid gallery entry`. These errors are added to the page you are rendering, and can be viewed by inspecting `errors`. For example:

```python
p = Page("my_page.mediawiki")
p.render("<gallery>..")
print(p.errors)
```

You get this error, as with `wikitexthtml` entries in a gallery have to start with `File:`. As you might have noticed in more places, `wikitexthtml` tends to be more strict about these things than MediaWiki. We did this to prevent people from making mistakes, as sometimes people think they are writing the caption, but are actually referencing an image.

Hope I analyzed the problem right; if not, let me know! And good luck with your quest to learning Python .. it is an awesome language worth learning :)

And ofc, if you find any other bugs or problems, also let me know!

PS: you remind me that I really should make more test-cases and write a better README for this repository .. might do that some day soon :)

**Comment by sonn-gamm** [comment]
Thanks! Adding types and the optional None fixed it. I forgot I could not omit types as I'm using a third-party module. Learning types now.

Expanding a bit upon the README would be very helpful. I took my time to read through the codebase and the examples, and avoided to reach out a few times already. The codebase is quite instructive on the other side!
